name: Test Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'John Doe'
      greeting:
        description: 'Greeting message'
        required: false
        default: 'Hello'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print greeting
      run: |
        echo "${{ github.event.inputs.greeting }}, ${{ github.event.inputs.name }}!"
